name = "pastebin"
compatibility_date = "2023-01-28"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = false
main = "src/index.js"

rules = [
  { type = "Text", globs = [ "*/frontend/**", "*/doc/**" ], fallthrough = true }
]

#----------------------------------------
# lines below are what you should modify
#----------------------------------------

[[routes]]
# Refer to https://developers.cloudflare.com/workers/wrangler/configuration/#routes
pattern = "p.apeiria.net"
custom_domain = true

[[kv_namespaces]]
binding = "PB"  # do not touch this
id = "e485dfc7728c4c06860741da8a0dfb32"  # id of your KV namespace

[vars]
# must be consistent with your routes
BASE_URL = "https://p.apeiria.net"

# url to repo, displayed in index page
REPO = "https://github.com/MSKNET/pastebin-worker"

# url to favicon
FAVICON = "https://blog.apeiria.net/img/favicon-32x32.png"

# the name displayed in TOS
TOS_MAINTAINER = "Misaka13514"

# the email displayed in TOS
TOS_MAIL = "pb@apeiria.net"

# Cache-Control max-age for static pages
CACHE_STATIC_PAGE_AGE = 7200

# Cache-Control max-age for static pages
CACHE_PASTE_AGE = 600
